/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StaffRegistry } from "./StaffRegistry";
export * as factories from "./factories";
export { StaffRegistry__factory } from "./factories/StaffRegistry__factory";
