/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface StaffRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allBatchHashes"
      | "allStaffHashes"
      | "getPayrollBatch"
      | "getStaffRecord"
      | "getTotalBatches"
      | "getTotalStaff"
      | "isBatchRecorded"
      | "isStaffActive"
      | "isStaffRegistered"
      | "owner"
      | "payrollBatches"
      | "recordPayrollBatch"
      | "registerStaff"
      | "revokeStaff"
      | "staffRecords"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PayrollBatchRecorded"
      | "StaffRegistered"
      | "StaffRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allBatchHashes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allStaffHashes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayrollBatch",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStaffRecord",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalBatches",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalStaff",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isBatchRecorded",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isStaffActive",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isStaffRegistered",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payrollBatches",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordPayrollBatch",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerStaff",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeStaff",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "staffRecords",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "allBatchHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allStaffHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPayrollBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStaffRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalBatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalStaff",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBatchRecorded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isStaffActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isStaffRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payrollBatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordPayrollBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerStaff",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeStaff",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "staffRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace PayrollBatchRecordedEvent {
  export type InputTuple = [
    batchHash: BytesLike,
    uploadedBy: AddressLike,
    timestamp: BigNumberish,
    staffCount: BigNumberish
  ];
  export type OutputTuple = [
    batchHash: string,
    uploadedBy: string,
    timestamp: bigint,
    staffCount: bigint
  ];
  export interface OutputObject {
    batchHash: string;
    uploadedBy: string;
    timestamp: bigint;
    staffCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StaffRegisteredEvent {
  export type InputTuple = [
    staffHash: BytesLike,
    registeredBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    staffHash: string,
    registeredBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    staffHash: string;
    registeredBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StaffRevokedEvent {
  export type InputTuple = [
    staffHash: BytesLike,
    revokedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    staffHash: string,
    revokedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    staffHash: string;
    revokedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StaffRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): StaffRegistry;
  waitForDeployment(): Promise<this>;

  interface: StaffRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allBatchHashes: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  allStaffHashes: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getPayrollBatch: TypedContractMethod<
    [_batchHash: BytesLike],
    [
      [string, string, bigint, bigint] & {
        batchHash: string;
        uploadedBy: string;
        timestamp: bigint;
        staffCount: bigint;
      }
    ],
    "view"
  >;

  getStaffRecord: TypedContractMethod<
    [_staffHash: BytesLike],
    [
      [string, string, bigint, boolean] & {
        staffHash: string;
        registeredBy: string;
        registeredAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getTotalBatches: TypedContractMethod<[], [bigint], "view">;

  getTotalStaff: TypedContractMethod<[], [bigint], "view">;

  isBatchRecorded: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  isStaffActive: TypedContractMethod<
    [_staffHash: BytesLike],
    [boolean],
    "view"
  >;

  isStaffRegistered: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  payrollBatches: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint] & {
        batchHash: string;
        uploadedBy: string;
        timestamp: bigint;
        staffCount: bigint;
      }
    ],
    "view"
  >;

  recordPayrollBatch: TypedContractMethod<
    [_batchHash: BytesLike, _staffCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerStaff: TypedContractMethod<
    [_staffHash: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeStaff: TypedContractMethod<
    [_staffHash: BytesLike],
    [void],
    "nonpayable"
  >;

  staffRecords: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean] & {
        staffHash: string;
        registeredBy: string;
        registeredAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allBatchHashes"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "allStaffHashes"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPayrollBatch"
  ): TypedContractMethod<
    [_batchHash: BytesLike],
    [
      [string, string, bigint, bigint] & {
        batchHash: string;
        uploadedBy: string;
        timestamp: bigint;
        staffCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStaffRecord"
  ): TypedContractMethod<
    [_staffHash: BytesLike],
    [
      [string, string, bigint, boolean] & {
        staffHash: string;
        registeredBy: string;
        registeredAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalBatches"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalStaff"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isBatchRecorded"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isStaffActive"
  ): TypedContractMethod<[_staffHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isStaffRegistered"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payrollBatches"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint] & {
        batchHash: string;
        uploadedBy: string;
        timestamp: bigint;
        staffCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordPayrollBatch"
  ): TypedContractMethod<
    [_batchHash: BytesLike, _staffCount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerStaff"
  ): TypedContractMethod<[_staffHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeStaff"
  ): TypedContractMethod<[_staffHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "staffRecords"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean] & {
        staffHash: string;
        registeredBy: string;
        registeredAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "PayrollBatchRecorded"
  ): TypedContractEvent<
    PayrollBatchRecordedEvent.InputTuple,
    PayrollBatchRecordedEvent.OutputTuple,
    PayrollBatchRecordedEvent.OutputObject
  >;
  getEvent(
    key: "StaffRegistered"
  ): TypedContractEvent<
    StaffRegisteredEvent.InputTuple,
    StaffRegisteredEvent.OutputTuple,
    StaffRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "StaffRevoked"
  ): TypedContractEvent<
    StaffRevokedEvent.InputTuple,
    StaffRevokedEvent.OutputTuple,
    StaffRevokedEvent.OutputObject
  >;

  filters: {
    "PayrollBatchRecorded(bytes32,address,uint256,uint256)": TypedContractEvent<
      PayrollBatchRecordedEvent.InputTuple,
      PayrollBatchRecordedEvent.OutputTuple,
      PayrollBatchRecordedEvent.OutputObject
    >;
    PayrollBatchRecorded: TypedContractEvent<
      PayrollBatchRecordedEvent.InputTuple,
      PayrollBatchRecordedEvent.OutputTuple,
      PayrollBatchRecordedEvent.OutputObject
    >;

    "StaffRegistered(bytes32,address,uint256)": TypedContractEvent<
      StaffRegisteredEvent.InputTuple,
      StaffRegisteredEvent.OutputTuple,
      StaffRegisteredEvent.OutputObject
    >;
    StaffRegistered: TypedContractEvent<
      StaffRegisteredEvent.InputTuple,
      StaffRegisteredEvent.OutputTuple,
      StaffRegisteredEvent.OutputObject
    >;

    "StaffRevoked(bytes32,address,uint256)": TypedContractEvent<
      StaffRevokedEvent.InputTuple,
      StaffRevokedEvent.OutputTuple,
      StaffRevokedEvent.OutputObject
    >;
    StaffRevoked: TypedContractEvent<
      StaffRevokedEvent.InputTuple,
      StaffRevokedEvent.OutputTuple,
      StaffRevokedEvent.OutputObject
    >;
  };
}
